# -*- coding: utf-8 -*-
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional

@dataclass
class PolicyDraft:
    """
    Represents a policy draft generated by a single Leukocyte (Phase 1).
    """
    policy_version: int
    target_endpoint: str
    minimum_allowed_fields: List[str]
    source_leukocyte_id: str
    timestamp: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

@dataclass
class MergedPolicy:
    """
    Represents a merged and verified policy (Phase 2).
    """
    target_endpoint: str
    policy_version: int
    minimum_allowed_fields: List[str]
    source_leukocytes: List[str]
    merged_timestamp: str
    verification_status: str = "PENDING"
    verification_notes: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

@dataclass
class ExecutionArtifact:
    """
    Represents the final compiled artifact for the Data Plane (Phase 3).
    """
    artifact_version: str
    target_endpoint: str
    action: str
    allowed_fields_map: Dict[str, int]
    metadata: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
